shell.run("main allthemodium:allthemodium_block 1")
shell.run("main minecraft:gold_block 1")

shell.run("main minecraft:clock 4")
shell.run("main minecraft:stick 1")
shell.run("main minecraft:repeater 8")

shell.run("main minecraft:oak_planks 24")
shell.run("main minecraft:diamond_block 1")
shell.run("main minecraft:glowstone 2")
shell.run("main minecraft:lapis_block 256")
shell.run("main minecraft:quartz_block 6")
shell.run("main minecraft:iron_block 12")
shell.run("main minecraft:piston 32")
shell.run("main solarflux:mirror 319")
shell.run("main solarflux:sp_1 256")
shell.run("main solarflux:sp_2 32")
shell.run("main solarflux:photovoltaic_cell_1 45")
shell.run("main solarflux:sp_3 8")
shell.run("main solarflux:photovoltaic_cell_2 21")
shell.run("main solarflux:sp_4 4")
shell.run("main solarflux:photovoltaic_cell_3 9")
shell.run("main solarflux:sp_5 2")
shell.run("main solarflux:blazing_coating 5")

shell.run("main solarflux:photovoltaic_cell_4 3")
shell.run("main solarflux:sp_custom_allthemodium 2")