shell.run("mkdir lib")
shell.run("cd lib")
shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/lib/class.lua")
shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/lib/json.lua")
shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/lib/list.lua")
shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/lib/util.lua")
shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/lib/tbl.lua")
shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/lib/ouroboros.lua")
shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/lib/set.lua")
shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/lib/backpack.lua")
shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/lib/crafter.lua")
shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/lib/rollup.lua")
shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/lib/planner.lua")
shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/lib/prompt.lua")
shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/lib/search.lua")
shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/lib/algorithm.lua")
shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/lib/node.lua")
shell.run("cd ..")


shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/plan.lua")
shell.run("wget https://raw.githubusercontent.com/GuitarMusashi616/AutoCrafter/master/craft.lua")